# Generated by Django 4.2.1 on 2023-05-11 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_author_alter_article_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelTable(
            name='article',
            table=None,
        ),
    ]
